version: "3.9"

services:
  server:
    environment:
      - NODE_ENV=development
    container_name: express
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - 4000:4000
    command: >
      sh -c "npm run dev"
    volumes:
      - ./src/src:/app/src
      - /app/node_modules/
