version: "3.9"

services:
  mariadb:
    image: mariadb:11.1.3
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mariadb/data:/var/lib/mysql/data/
    environment:
      MYSQL_ROOT_PASSWORD: XShWJZbkijODfSsJfUHw
      MYSQL_DATABASE: login
      MYSQL_USER: bengali
      MYSQL_PASSWORD: IqggGBfYniKzbuqSOdRV
    ports:
      - 3306:3306
