version: "3.9"

services:
  node:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: unless-stopped
    ports:
      - 5000:5000
    command: >
      sh -c "npm run dev"
    volumes:
      - ./src/src:/app/src
      - /app/node_modules/
